name: ExplosionRegen
main: gipsyking.explosionregen.ExplosionRegen
version: 0.2
depend: [Factions]
commands:
  explosionregen:
    description: Regenerate explosions
    permission: explosionregen.command
    usage: /<command> [regen]
permissions:
  explosionregen.*:
    description: Everything explosion regeneration related. For admins only.
    children:
      explosionregen.command: true
  explosionregen.command:
    description: explosionregeb command
