name: ExplosionRegen
main: gipsyking.explosionregen.ExplosionRegen
version: 0.2
commands:
  explosionregen:
    description: Regenerate explosions now or get info
    permission: explosionregen.command
    usage: /<command> [info]

